/* Fluxcord frontend core */
const SUPABASE_CDN='https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2';
let supabaseClient=null,dbProducts=[],configLoaded=false;
const FALLBACK_PRODUCTS=[
{id:'demo-1',title:'Discord Bot Development Master Prompt',category:'AI Master Prompts',price:.99,currency:'USD',image_url:'https://i.imgur.com/1t8xktU.png',description:'AI-powered master prompt for building Discord bots.',featured:true,is_active:true,download_url:''},
{id:'demo-2',title:'Telegram Bot Development Master Prompt',category:'AI Master Prompts',price:.99,currency:'USD',image_url:'https://i.imgur.com/C9C07Wo.png',description:'A practical master prompt for Telegram bot development.',featured:true,is_active:true,download_url:''},
{id:'demo-3',title:'Ultimate E-Book Creator Guide',category:'E-Books',price:4.99,currency:'USD',image_url:'https://i.imgur.com/x92sVrE.png',description:'A digital guide for creating better e-books.',featured:true,is_active:true,download_url:''},
{id:'demo-4',title:'Discord Moderation Bot',category:'Discord Bots',price:7.99,currency:'USD',image_url:'https://i.imgur.com/4p4bYNV.png',description:'Ready-to-use Discord moderation resource.',featured:false,is_active:true,download_url:''},
{id:'demo-5',title:'Telegram Auto Reply Bot',category:'Telegram Bots',price:5.99,currency:'USD',image_url:'https://i.imgur.com/C9C07Wo.png',description:'Automation resource for Telegram communities.',featured:false,is_active:true,download_url:''},
{id:'demo-6',title:'Creator Portfolio Website',category:'Pre-Made Websites',price:12.99,currency:'USD',image_url:'https://i.imgur.com/ibq6soB.png',description:'A polished starter portfolio website.',featured:false,is_active:true,download_url:''},
{id:'demo-7',title:'AI Freelancing Starter Pack',category:'Others',price:3.99,currency:'USD',image_url:'https://i.imgur.com/GNBtqxq.png',description:'Starter resources for digital freelancing.',featured:false,is_active:true,download_url:''},
{id:'demo-8',title:'Game Server Setup Toolkit',category:'Games',price:8.99,currency:'USD',image_url:'https://i.imgur.com/bzSzLYN.jpeg',description:'Tools and guides for game server setup.',featured:false,is_active:true,download_url:''}];
function $(s){return document.querySelector(s)} function $all(s){return [...document.querySelectorAll(s)]}
function toast(message,type='info'){let b=$('#fluxToast');if(!b){b=document.createElement('div');b.id='fluxToast';b.style.cssText='position:fixed;right:20px;bottom:20px;z-index:99999;max-width:390px;padding:14px 16px;border:1px solid #ffffff18;border-radius:12px;background:#11141c;color:#f4f4f6;box-shadow:0 18px 50px #0008;font:600 14px/1.4 DM Sans,Arial';document.body.appendChild(b)}b.textContent=message;b.style.borderColor=type==='error'?'#ef4444':type==='success'?'#22c55e':'#ffffff18';clearTimeout(window.__toastTimer);window.__toastTimer=setTimeout(()=>b.remove(),4500)}
function escapeHtml(v){return String(v??'').replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]))}
function slugify(v){return String(v||'').toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'')}
function getCart(){try{return JSON.parse(localStorage.getItem('fluxcord_cart')||'{}')}catch{return{}}}
function saveCart(c){localStorage.setItem('fluxcord_cart',JSON.stringify(c));updateCartCount()}
function updateCartCount(){const n=Object.values(getCart()).reduce((a,b)=>a+Number(b||0),0);$all('#cartCount').forEach(e=>e.textContent=n)}
function normalizeProduct(p){return{id:p.id,title:p.title||p.name||'Untitled',name:p.title||p.name||'Untitled',category:p.category||p.cat||'Others',cat:p.category||p.cat||'Others',price:Number(p.price||0),currency:p.currency||'USD',image_url:p.image_url||'',description:p.description||'',download_url:p.download_url||'',is_active:p.is_active!==false,featured:!!p.featured,rating:Number(p.rating||5),badge:p.badge||'NEW',tag:p.tag||String(p.category||p.cat||'DIGITAL').toUpperCase()}}
async function loadSupabase(){if(configLoaded)return supabaseClient;configLoaded=true;try{const r=await fetch('/api/config',{cache:'no-store'});if(!r.ok)throw Error('Config endpoint unavailable');const cfg=await r.json();if(!window.supabase||typeof window.supabase.createClient!=='function')await new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=SUPABASE_CDN;s.async=false;s.onload=()=>window.supabase?.createClient?resolve():reject(Error('Supabase client unavailable'));s.onerror=()=>reject(Error('Could not load Supabase client'));document.head.appendChild(s)});supabaseClient=window.supabase.createClient(cfg.url,cfg.key,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true,storageKey:'fluxcord-auth',storage:'localStorage'}});return supabaseClient}catch(e){console.error(e);toast(e.message||'Supabase could not be initialized.','error');return null}}
async function initProducts(){const sb=await loadSupabase();if(!sb){dbProducts=FALLBACK_PRODUCTS.map(normalizeProduct);return dbProducts}const {data,error}=await sb.from('products').select('*').eq('is_active',true).order('created_at',{ascending:false});if(error){console.error(error);dbProducts=FALLBACK_PRODUCTS.map(normalizeProduct);return dbProducts}dbProducts=(data||[]).map(normalizeProduct);return dbProducts}
async function currentUser(){const sb=await loadSupabase();if(!sb)return null;const {data}=await sb.auth.getUser();return data?.user||null}
async function currentProfile(){const sb=await loadSupabase(),u=await currentUser();if(!sb||!u)return null;const {data}=await sb.from('profiles').select('*').eq('id',u.id).maybeSingle();return data||null}
function productUrl(p){return '/'+encodeURIComponent(slugify(p.category))+'/'+encodeURIComponent(slugify(p.title))}
function productCard(p){p=normalizeProduct(p);const img=p.image_url?`<img src="${escapeHtml(p.image_url)}" alt="${escapeHtml(p.name)}" loading="lazy">`:`<div class="mock">${escapeHtml(p.tag)}</div>`;return `<article class="product" onclick="openProduct('${escapeHtml(p.id)}')"><div class="product-img"><span class="badge">${escapeHtml(p.badge)}</span>${img}</div><div class="product-body"><span class="category-label">${escapeHtml(p.cat)}</span><h3>${escapeHtml(p.name)}</h3><div class="stars">★★★★★ <small>${p.rating.toFixed(1)}</small></div><div class="product-foot"><span class="price">$${p.price.toFixed(2)}</span><div class="product-actions"><button class="add" onclick="event.stopPropagation();addToCart('${escapeHtml(p.id)}')">Add to Cart</button><button class="btn small" onclick="event.stopPropagation();openProduct('${escapeHtml(p.id)}')">Buy Now →</button></div></div></div></article>`}
async function openProduct(id){const list=dbProducts.length?dbProducts:await initProducts();const p=list.find(x=>String(x.id)===String(id));if(p)location.href=productUrl(p)}
async function renderHome(){if(!$('#featured')&&!$('#newArrivals'))return;const list=await initProducts();if($('#featured'))$('#featured').innerHTML=list.filter(p=>p.featured).slice(0,6).map(productCard).join('')||list.slice(0,6).map(productCard).join('');if($('#newArrivals'))$('#newArrivals').innerHTML=list.slice(0,8).map(productCard).join('')}
async function addToCart(id){const list=dbProducts.length?dbProducts:await initProducts(),p=list.find(x=>String(x.id)===String(id));if(!p)return toast('This product is not available.','error');const c=getCart();c[id]=(c[id]||0)+1;saveCart(c);toast('Added to cart.','success')}
function getCartProducts(){return Object.entries(getCart()).map(([id,q])=>{const p=dbProducts.find(x=>String(x.id)===String(id))||FALLBACK_PRODUCTS.map(normalizeProduct).find(x=>String(x.id)===String(id));return p?{...p,q:Number(q)}:null}).filter(Boolean)}
async function hydrateCartProducts(){if(!dbProducts.length)await initProducts();return getCartProducts()}
async function renderCart(){const area=$('#cartArea');if(!area)return;const items=await hydrateCartProducts();if(!items.length){area.innerHTML='<div class="panel" style="text-align:center;padding:70px"><h2>Your cart is empty</h2><p>Start shopping for premium digital resources.</p><a class="btn" href="shop.html">Start Shopping</a></div>';return}const total=items.reduce((s,p)=>s+p.price*p.q,0);area.innerHTML=`<div class="cart-layout"><section class="panel"><div class="cart-row cart-head"><span>Product</span><span></span><span>Qty</span><span>Subtotal</span><span></span></div>${items.map(p=>`<div class="cart-row"><div class="thumb"><img src="${escapeHtml(p.image_url||'')}" alt=""></div><div><b>${escapeHtml(p.name)}</b><small>${escapeHtml(p.cat)}</small></div><div class="qty"><button onclick="changeQty('${escapeHtml(p.id)}',-1)">−</button><input value="${p.q}" onchange="setQty('${escapeHtml(p.id)}',this.value)"><button onclick="changeQty('${escapeHtml(p.id)}',1)">+</button></div><strong>$${(p.price*p.q).toFixed(2)}</strong><button class="remove" onclick="removeItem('${escapeHtml(p.id)}')">×</button></div>`).join('')}<a class="btn outline" href="shop.html">← Continue Shopping</a></section><aside class="panel summary"><h2>Order Summary</h2><div><span>Subtotal</span><strong>$${total.toFixed(2)}</strong></div><hr><div><strong>Total</strong><strong class="price">$${total.toFixed(2)}</strong></div><button class="btn full" onclick="startCartCheckout()">Proceed to Checkout →</button></aside></div>`}
async function startCartCheckout(){const items=await hydrateCartProducts();if(!items.length)return toast('Your cart is empty.','error');if(items.length===1)return openProduct(items[0].id);toast('For multi-product carts, select a product and confirm the order from its product page.','info')}
function changeQty(id,n){const c=getCart();c[id]=Math.max(1,Math.min(99,(c[id]||1)+n));saveCart(c);renderCart()}function setQty(id,n){const c=getCart();c[id]=Math.max(1,Math.min(99,Number(n)||1));saveCart(c);renderCart()}function removeItem(id){const c=getCart();delete c[id];saveCart(c);renderCart()}
async function renderShop(){const grid=$('#shopGrid');if(!grid)return;const list=await initProducts(),q=new URLSearchParams(location.search),cat=q.get('cat')||'';if(cat&&$('#category'))$('#category').value=cat;const min=$('#priceMin'),max=$('#priceMax');function draw(){let a=Number(min?.value||0),b=Number(max?.value||100);if(a>b){if(document.activeElement===min){a=b;min.value=a}else{b=a;max.value=b}}if($('#priceMinLabel'))$('#priceMinLabel').textContent='$'+a.toFixed(2);if($('#priceMaxLabel'))$('#priceMaxLabel').textContent='$'+b.toFixed(2);let arr=list.filter(p=>(!$('#category')?.value||p.cat===$('#category').value)&&p.price>=a&&p.price<=b);const sort=$('#sort')?.value;if(sort==='low')arr.sort((x,y)=>x.price-y.price);if(sort==='high')arr.sort((x,y)=>y.price-x.price);if(sort==='rating')arr.sort((x,y)=>y.rating-x.rating);if($('#results'))$('#results').textContent=`Showing ${arr.length} result${arr.length===1?'':'s'}`;grid.innerHTML=arr.length?arr.map(productCard).join(''):'<div class="panel"><h2>No products found</h2><p>Clear your filters and try again.</p></div>'}min?.addEventListener('input',draw);max?.addEventListener('input',draw);$('#category')?.addEventListener('change',draw);$('#sort')?.addEventListener('change',draw);draw();window.clearFilters=()=>{if($('#category'))$('#category').value=cat;if(min)min.value=0;if(max)max.value=100;draw()}}
async function handleLogin(e){e.preventDefault();const sb=await loadSupabase();if(!sb)return;const email=$('#loginEmail').value.trim().toLowerCase(),password=$('#loginPassword').value;const {error}=await sb.auth.signInWithPassword({email,password});if(error)return toast(error.message,'error');const next=new URLSearchParams(location.search).get('next');const profile=await currentProfile();location.href=next?decodeURIComponent(next):(profile?.role==='admin'?'admin.html':'account.html')}
async function handleRegister(e){e.preventDefault();const first=$('#firstName').value.trim(),last=$('#lastName').value.trim(),email=$('#registerEmail').value.trim(),password=$('#registerPassword').value,confirm=$('#registerConfirm').value;if(password!==confirm)return toast('Passwords do not match.','error');if(!confirm('Create your Fluxcord account with '+email+'?'))return;const btn=e.submitter||e.target.querySelector('button[type=submit]');if(btn){btn.disabled=true;btn.textContent='Sending confirmation…'}try{const r=await fetch('/api/auth-email',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'register',firstName:first,lastName:last,email,password})}),data=await r.json().catch(()=>({}));if(!r.ok)throw Error(data.error||'Could not create your account.');toast(data.message||'Check your email.','success');setTimeout(()=>location.href='login.html?confirmed=0',1000)}catch(err){toast(err.message,'error')}finally{if(btn){btn.disabled=false;btn.textContent='Create Account'}}}
async function sendMagicLink(){const email=$('#loginEmail')?.value.trim().toLowerCase();if(!email)return toast('Enter your email address first.','error');if(!confirm('Send a sign-in link to '+email+'?'))return;try{const r=await fetch('/api/auth-email',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'magiclink',email})}),d=await r.json();if(!r.ok)throw Error(d.error||'Could not send sign-in link.');toast(d.message,'success')}catch(e){toast(e.message,'error')}}
async function sendResetLink(){const email=$('#loginEmail')?.value.trim().toLowerCase();if(!email)return toast('Enter your email address first.','error');if(!confirm('Send a password-reset email to '+email+'?'))return;try{const r=await fetch('/api/auth-email',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'recovery',email})}),d=await r.json();if(!r.ok)throw Error(d.error||'Could not send reset email.');toast(d.message,'success')}catch(e){toast(e.message,'error')}}
function forgotEmail(){toast('Use the email address you used when creating your Fluxcord account. If you cannot remember it, contact Fluxcord support.','info')}
async function logout(){const sb=await loadSupabase();if(sb)await sb.auth.signOut({scope:'local'});location.href='index.html'}
async function requireUser(){const u=await currentUser();if(!u){location.href='login.html?next='+encodeURIComponent(location.pathname+location.search);return null}return u}
async function renderAccount(){const user=await requireUser();if(!user)return;const profile=await currentProfile();if($('#accountName'))$('#accountName').textContent=profile?.full_name||user.email?.split('@')[0]||'Customer';if($('#accountEmail'))$('#accountEmail').textContent=user.email||'';if($('#accountAvatar'))$('#accountAvatar').textContent=(profile?.full_name||user.email||'U').slice(0,2).toUpperCase();const sb=await loadSupabase();const {data:orders}=await sb.from('orders').select('*,order_items(*)').eq('user_id',user.id).order('created_at',{ascending:false});const rows=orders||[];if($('#totalOrders'))$('#totalOrders').textContent=rows.length;if($('#deliveredOrders'))$('#deliveredOrders').textContent=rows.filter(o=>o.status==='delivered').length;if($('#totalSpent'))$('#totalSpent').textContent='$'+rows.reduce((s,o)=>s+Number(o.total||0),0).toFixed(2);const box=$('#ordersList');if(box)box.innerHTML=rows.length?rows.map(o=>`<div class="order-card"><div><b>Order #${escapeHtml(o.id.slice(0,8))}</b><small>${new Date(o.created_at).toLocaleString()}</small></div><span class="status ${escapeHtml(o.status)}">${escapeHtml(o.status.replace('_',' '))}</span><strong>$${Number(o.total).toFixed(2)}</strong><a class="btn small outline" href="/checkout/${o.id}">View</a></div>`).join(''):'<p>No orders yet. Start shopping to see your purchases here.</p>'}
async function renderAdmin(){const u=await requireUser();if(!u)return;const profile=await currentProfile();if(profile?.role!=='admin'){toast('Admin access required.','error');location.href='account.html';return}await loadAdminProducts();await loadAdminOrders();await loadAdminReviews();await loadAdminCustomers();const sb=await loadSupabase(),{count:customers}=await sb.from('profiles').select('id',{count:'exact',head:true}),{data:orders}=await sb.from('orders').select('status,total');const list=orders||[];if($('#adminCustomers'))$('#adminCustomers').textContent=customers??0;if($('#adminOrders'))$('#adminOrders').textContent=list.length;if($('#adminSales'))$('#adminSales').textContent='$'+list.reduce((s,o)=>s+Number(o.total||0),0).toFixed(2);['pending','under_review','delivered','cancelled','refunded'].forEach(st=>{if($('#count_'+st))$('#count_'+st).textContent=list.filter(o=>o.status===st).length})}
async function loadAdminProducts(){const sb=await loadSupabase(),{data,error}=await sb.from('products').select('*').order('created_at',{ascending:false});if(error)return toast(error.message,'error');const box=$('#adminProducts');if(box)box.innerHTML=(data||[]).map(p=>`<div class="admin-product"><div><b>${escapeHtml(p.title)}</b><small>${escapeHtml(p.category)} · $${Number(p.price).toFixed(2)} · ${p.is_active?'Active':'Hidden'}</small></div><div><button class="btn small" onclick="editProduct('${p.id}')">Edit</button> <button class="btn small outline" onclick="deleteProduct('${p.id}')">Delete</button></div></div>`).join('')||'<p>No products yet.</p>';window.__adminProducts=data||[]}
function openProductForm(p=null){const f=$('#productForm');if(!f)return;f.reset();$('#productId').value=p?.id||'';$('#productTitle').value=p?.title||'';$('#productCategory').value=p?.category||'Others';$('#productPrice').value=p?.price??'';$('#productImage').value=p?.image_url||'';$('#productDownload').value=p?.download_url||'';$('#productDescription').value=p?.description||'';$('#productActive').checked=p?.is_active!==false;$('#productFeatured').checked=!!p?.featured;$('#productModal').style.display='flex'}
function closeProductForm(){if($('#productModal'))$('#productModal').style.display='none'} function editProduct(id){openProductForm((window.__adminProducts||[]).find(p=>p.id===id)||null)}
async function saveProduct(e){e.preventDefault();const sb=await loadSupabase(),id=$('#productId').value,payload={title:$('#productTitle').value.trim(),slug:slugify($('#productTitle').value),category:$('#productCategory').value,price:Number($('#productPrice').value||0),currency:'USD',image_url:$('#productImage').value.trim()||null,download_url:$('#productDownload').value.trim()||null,description:$('#productDescription').value.trim()||null,is_active:$('#productActive').checked,featured:$('#productFeatured').checked};const q=id?sb.from('products').update(payload).eq('id',id):sb.from('products').insert(payload);const {error}=await q;if(error)return toast(error.message,'error');closeProductForm();toast(id?'Product updated.':'Product created.','success');await loadAdminProducts();await initProducts()}
async function deleteProduct(id){if(!confirm('Delete this product?'))return;const sb=await loadSupabase(),{error}=await sb.from('products').delete().eq('id',id);if(error)return toast(error.message,'error');toast('Product deleted.','success');loadAdminProducts()}
async function loadAdminOrders(){const sb=await loadSupabase(),{data,error}=await sb.from('orders').select('*,profiles(email,full_name),order_items(*)').order('created_at',{ascending:false});if(error)return toast(error.message,'error');window.__adminOrders=data||[];const box=$('#adminOrdersList');if(!box)return;const pending=(data||[]).filter(o=>['pending','under_review'].includes(o.status));box.innerHTML=(data||[]).map(o=>`<div class="admin-order"><div class="admin-order-head"><div><b>#${o.id.slice(0,8)}</b><small>${escapeHtml(o.profiles?.full_name||'')} · ${escapeHtml(o.profiles?.email||'')} · ${new Date(o.created_at).toLocaleString()}</small></div><strong>$${Number(o.total).toFixed(2)}</strong></div><div class="admin-order-items">${(o.order_items||[]).map(i=>`<span>${escapeHtml(i.product_title)} × ${i.quantity}</span>`).join('')}</div><p class="order-meta">Payment: <b>${escapeHtml(o.payment_method||'')}</b> · Sender: <b>${escapeHtml(o.payment_sender||'—')}</b> · TXID: <b>${escapeHtml(o.payment_reference||'—')}</b></p><div class="admin-order-actions"><span class="status ${o.status}">${escapeHtml(o.status.replace('_',' '))}</span>${pending?`<button class="btn small" onclick="adminOrderAction('${o.id}','delivered')">Delivered</button><button class="btn small outline" onclick="adminOrderAction('${o.id}','cancelled')">Cancelled</button>`:''}<button class="btn small outline" onclick="saveOrderNote('${o.id}')">Save Note</button><input id="note_${o.id}" value="${escapeHtml(o.admin_note||'')}" placeholder="Admin note"></div></div>`).join('')||'<p>No orders yet.</p>'}
async function adminOrderAction(id,action){if(!confirm(action==='delivered'?'Mark this order delivered and email the customer?':'Cancel this order and email the customer?'))return;const sb=await loadSupabase(),session=(await sb.auth.getSession()).data.session;if(!session)return;try{const r=await fetch('/api/order-action',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+session.access_token},body:JSON.stringify({orderId:id,action})}),d=await r.json();if(!r.ok)throw Error(d.error||'Order action failed');toast(d.message,'success');await loadAdminOrders()}catch(e){toast(e.message,'error')}}
async function saveOrderNote(id){const sb=await loadSupabase(),note=$('#note_'+id)?.value.trim()||null,{error}=await sb.from('orders').update({admin_note:note}).eq('id',id);if(error)return toast(error.message,'error');toast('Note saved.','success')}
async function loadAdminReviews(){const box=$('#adminReviews');if(!box)return;const sb=await loadSupabase(),{data,error}=await sb.from('reviews').select('*,products(title)').order('created_at',{ascending:false});if(error)return toast(error.message,'error');window.__adminReviews=data||[];box.innerHTML=(data||[]).map(r=>`<div class="admin-review"><div><b>${escapeHtml(r.reviewer_name||'Customer')}</b> · ${'★'.repeat(r.rating)}<small>${escapeHtml(r.products?.title||'')}</small></div><p>${escapeHtml(r.review_text)}</p><div><button class="btn small" onclick="editReview('${r.id}')">Edit</button> <button class="btn small outline" onclick="deleteReview('${r.id}')">Delete</button> <button class="btn small outline" onclick="toggleReview('${r.id}',${!r.is_approved})">${r.is_approved?'Hide':'Approve'}</button></div></div>`).join('')||'<p>No reviews yet.</p>'}
function editReview(id){const r=(window.__adminReviews||[]).find(x=>x.id===id);if(!r)return;const text=prompt('Review message:',r.review_text);if(text===null)return;const name=prompt('Reviewer name:',r.reviewer_name||'Customer');if(name===null)return;saveReviewEdit(id,text,name)}
async function saveReviewEdit(id,text,name){const sb=await loadSupabase(),{error}=await sb.from('reviews').update({review_text:text.trim(),reviewer_name:name.trim()}).eq('id',id);if(error)return toast(error.message,'error');toast('Review updated.','success');loadAdminReviews()}
async function deleteReview(id){if(!confirm('Delete this review?'))return;const sb=await loadSupabase(),{error}=await sb.from('reviews').delete().eq('id',id);if(error)return toast(error.message,'error');loadAdminReviews()}
async function toggleReview(id,approved){const sb=await loadSupabase(),{error}=await sb.from('reviews').update({is_approved:approved}).eq('id',id);if(error)return toast(error.message,'error');loadAdminReviews()}
async function addFakeReview(){const name=prompt('Reviewer name:');if(!name)return;const productId=prompt('Product UUID (copy it from Products):');if(!productId)return;const rating=Math.max(1,Math.min(5,Number(prompt('Rating 1-5:','5'))||5));const text=prompt('Review message:');if(!text)return;const sb=await loadSupabase(),{error}=await sb.from('reviews').insert({user_id:null,product_id:productId,rating,title:'',review_text:text.trim(),reviewer_name:name.trim(),is_approved:true});if(error)return toast(error.message,'error');toast('Fake review added.','success');loadAdminReviews()}
async function loadAdminCustomers(){const box=$('#adminCustomersList');if(!box)return;const sb=await loadSupabase(),{data,error}=await sb.from('profiles').select('id,email,full_name,role,balance,total_spend,created_at').order('created_at',{ascending:false});if(error)return toast(error.message,'error');window.__adminCustomers=data||[];box.innerHTML=(data||[]).map(c=>`<div class="admin-customer"><div><b>${escapeHtml(c.full_name||'Customer')}</b><small>${escapeHtml(c.email||'')} · ${c.role}</small></div><label>Balance <input id="bal_${c.id}" type="number" step="0.01" value="${Number(c.balance||0).toFixed(2)}"></label><label>Total spend <input id="spend_${c.id}" type="number" step="0.01" value="${Number(c.total_spend||0).toFixed(2)}"></label><button class="btn small" onclick="saveCustomer('${c.id}')">Save</button></div>`).join('')||'<p>No customers yet.</p>'}
async function saveCustomer(id){const sb=await loadSupabase(),balance=Number($('#bal_'+id)?.value||0),total_spend=Number($('#spend_'+id)?.value||0),{error}=await sb.from('profiles').update({balance,total_spend}).eq('id',id);if(error)return toast(error.message,'error');toast('Customer updated.','success')}
async function renderProductPage(){const box=$('#productDetail');if(!box)return;const q=new URLSearchParams(location.search),path=location.pathname.replace(/\/$/,'').split('/').filter(Boolean),category=q.get('category')|| (path.length>1?decodeURIComponent(path[0]):''),slug=q.get('product')|| (path.length>1?decodeURIComponent(path[1]):q.get('slug'));const list=await initProducts();let p=list.find(x=>slugify(x.title)===slug&&(!category||slugify(x.category)===category));if(!p&&slug)p=list.find(x=>slugify(x.title)===slug);if(!p){box.innerHTML='<div class="panel"><h1>Product not found</h1><a class="btn" href="shop.html">Back to Shop</a></div>';return}window.__currentProduct=p;const sb=await loadSupabase();let reviews=[];if(sb){const r=await sb.from('reviews').select('*').eq('product_id',p.id).eq('is_approved',true).order('created_at',{ascending:false});reviews=r.data||[]}box.innerHTML=`<div class="product-detail-grid"><section class="panel product-detail-media"><img src="${escapeHtml(p.image_url)}" alt="${escapeHtml(p.name)}"></section><section class="panel"><span class="eyebrow">${escapeHtml(p.category)}</span><h1>${escapeHtml(p.name)}</h1><div class="stars">★★★★★ ${p.rating.toFixed(1)}</div><p class="detail-description">${escapeHtml(p.description)}</p><div class="detail-price">$${p.price.toFixed(2)}</div><div class="payment-select"><label>Choose a Payment option<select id="detailPayment"><option>bKash</option><option>Nagad</option><option>Litecoin</option><option>Bitcoin</option><option>USDT</option></select></label></div><button class="btn full" onclick="confirmProductOrder()">Confirm Order →</button><button class="btn outline full" style="margin-top:10px" onclick="addToCart('${escapeHtml(p.id)}')">Add to Cart</button></section></div><section class="panel detail-section"><h2>Purchase history</h2><div id="purchaseHistory">${await renderPurchaseHistory(p.id)}</div></section><section class="panel detail-section"><div class="section-head"><h2>Reviews</h2><span>${reviews.length} review${reviews.length===1?'':'s'}</span></div><div class="review-list">${reviews.length?reviews.map(r=>`<article><b>${escapeHtml(r.reviewer_name||'Customer')}</b><span>${'★'.repeat(r.rating)}</span><p>${escapeHtml(r.review_text)}</p></article>`).join(''):'<p>No reviews yet.</p>'}</div></section>`}
async function renderPurchaseHistory(productId){const sb=await loadSupabase(),u=await currentUser();if(!sb||!u)return '<p>Sign in to view your purchase history for this product.</p>';const {data}=await sb.from('order_items').select('*,orders!inner(user_id,status,created_at)').eq('product_id',productId).eq('orders.user_id',u.id).order('created_at',{ascending:false});return data?.length?data.map(i=>`<div class="history-row"><span>${new Date(i.created_at).toLocaleDateString()}</span><span class="status ${i.orders.status}">${i.orders.status}</span></div>`).join(''):'<p>No previous purchases of this product.</p>'}
async function confirmProductOrder(){const u=await requireUser();if(!u)return;const p=window.__currentProduct;if(!p)return;const method=$('#detailPayment').value;const sb=await loadSupabase();const {data,error}=await sb.rpc('create_order',{p_items:[{product_id:p.id,quantity:1}],p_payment_method:method,p_payment_reference:null,p_payment_sender:null,p_customer_note:null});if(error){toast(error.message,'error');return}location.href='/checkout/'+data}
async function renderCheckoutPage(){const area=$('#orderCheckout');if(!area)return;const id=(location.pathname.match(/checkout\/([^/]+)/)||[])[1]||new URLSearchParams(location.search).get('order');if(!id)return;const sb=await loadSupabase(),u=await requireUser();if(!u)return;const {data:o,error}=await sb.from('orders').select('*,order_items(*)').eq('id',id).eq('user_id',u.id).single();if(error||!o){area.innerHTML='<div class="panel"><h1>Order not found</h1></div>';return}if(o.payment_reference){return renderOrderStatus(o)}const total=Number(o.total||0);area.innerHTML=`<div class="checkout"><section class="panel"><span class="eyebrow">ORDER #${escapeHtml(id.slice(0,8))}</span><h1>Complete payment</h1><p>Payment method: <b>${escapeHtml(o.payment_method||'')}</b></p><div id="cryptoAmount" class="crypto-box">Calculating payment amount…</div><label>Sender number / wallet ID<input id="paymentSender" placeholder="Your bKash/Nagad number or crypto sender/wallet ID"></label><label>TRXID / Transaction ID<input id="paymentReference" placeholder="Enter transaction ID / hash" required></label><div class="actions"><button class="btn outline" onclick="history.back()">← Go Back</button><button class="btn" onclick="submitPayment('${o.id}')">Submit →</button></div></section><aside class="panel summary"><h2>Order</h2>${(o.order_items||[]).map(i=>`<div><span>${escapeHtml(i.product_title)} × ${i.quantity}</span><strong>$${Number(i.line_total).toFixed(2)}</strong></div>`).join('')}<hr><div><strong>Total</strong><strong class="price">$${total.toFixed(2)}</strong></div></aside></div>`;updateCryptoAmount(total,o.payment_method)}
async function updateCryptoAmount(total,method){const box=$('#cryptoAmount');if(!box)return;if(['Bitcoin','Litecoin','USDT'].includes(method)){try{const r=await fetch('/api/crypto-rate?asset='+encodeURIComponent(method)+'&amount='+encodeURIComponent(total));const d=await r.json();if(d.rate)box.innerHTML=`<b>Payment amount</b><br>$${total.toFixed(2)} ≈ ${d.amount} ${escapeHtml(d.symbol)}<small>Rate: 1 ${escapeHtml(d.symbol)} ≈ $${Number(d.rate).toLocaleString()}</small>`;else box.textContent='$'+total.toFixed(2)}catch{box.textContent='$'+total.toFixed(2)}}else box.innerHTML=`<b>Amount to pay</b><br>$${total.toFixed(2)}`}
async function submitPayment(id){const sender=$('#paymentSender').value.trim(),ref=$('#paymentReference').value.trim();if(!sender||!ref)return toast('Enter both sender number/wallet ID and transaction ID.','error');const sb=await loadSupabase(),{error}=await sb.rpc('submit_payment',{p_order_id:id,p_payment_sender:sender,p_payment_reference:ref});if(error)return toast(error.message,'error');toast('Payment submitted.','success');await renderOrderStatusById(id)}
async function renderOrderStatusById(id){const sb=await loadSupabase(),{data:o}=await sb.from('orders').select('*,order_items(*)').eq('id',id).single();if(o)renderOrderStatus(o)}
function renderOrderStatus(o){const area=$('#orderCheckout');const delivered=o.status==='delivered',cancelled=o.status==='cancelled';const step=cancelled?'cancelled':delivered?'delivered':o.status==='under_review'?'under_review':'pending';area.innerHTML=`<div class="panel order-status-page"><span class="eyebrow">ORDER #${escapeHtml(o.id.slice(0,8))}</span><h1>Order status</h1><div class="status-timeline"><div class="done">Payment Send <b>✓</b></div><div class="${step==='under_review'||delivered?'done':''}">Under Review <b>${step==='under_review'||delivered?'✓':'○'}</b></div><div class="${delivered?'done':''}">${delivered?'Order Delivered':'Sending the order in your mail'} <b>${delivered?'✓':'⏳'}</b></div></div><h2>${cancelled?'Order cancelled':delivered?'Order delivered':'99% Done'}</h2><p>${cancelled?'This order has been cancelled.':delivered?'Your order has been delivered to your email. Keep an eye on your inbox.':'Order will be delivered in your mails. Keep an eye on them.'}</p><div class="panel-inner">${(o.order_items||[]).map(i=>`<div><b>${escapeHtml(i.product_title)}</b><span>$${Number(i.line_total).toFixed(2)}</span></div>`).join('')}</div>${delivered?'<p><a class="btn" href="account.html">Open My Account</a></p>':''}</div>`}
async function boot(){updateCartCount();if($('#featured')||$('#newArrivals'))renderHome();if($('#shopGrid'))renderShop();if($('#cartArea'))renderCart();if($('#accountName'))renderAccount();if($('#adminProducts')||$('#adminOrdersList'))renderAdmin();if($('#productDetail'))renderProductPage();if($('#orderCheckout'))renderCheckoutPage();$all('.footer-year').forEach(e=>e.textContent=new Date().getFullYear())}
document.addEventListener('DOMContentLoaded',boot);
function filterAdminOrders(filter,button){$all('.admin-tabs button').forEach(b=>b.classList.remove('active'));button?.classList.add('active');const all=window.__adminOrders||[];const list=filter==='all'?all:all.filter(o=>o.status===filter);const box=$('#adminOrdersList');if(!box)return;box.innerHTML=list.length?list.map(o=>{const pending=['pending','under_review'].includes(o.status);return `<div class="admin-order"><div class="admin-order-head"><div><b>#${o.id.slice(0,8)}</b><small>${escapeHtml(o.profiles?.full_name||'')} · ${escapeHtml(o.profiles?.email||'')} · ${new Date(o.created_at).toLocaleString()}</small></div><strong>$${Number(o.total).toFixed(2)}</strong></div><div class="admin-order-items">${(o.order_items||[]).map(i=>`<span>${escapeHtml(i.product_title)} × ${i.quantity}</span>`).join('')}</div><p class="order-meta">Payment: <b>${escapeHtml(o.payment_method||'')}</b> · Sender: <b>${escapeHtml(o.payment_sender||'—')}</b> · TXID: <b>${escapeHtml(o.payment_reference||'—')}</b></p><div class="admin-order-actions"><span class="status ${o.status}">${escapeHtml(o.status.replace('_',' '))}</span>${pending?`<button class="btn small" onclick="adminOrderAction('${o.id}','delivered')">Delivered</button><button class="btn small outline" onclick="adminOrderAction('${o.id}','cancelled')">Cancelled</button>`:''}<button class="btn small outline" onclick="saveOrderNote('${o.id}')">Save Note</button><input id="note_${o.id}" value="${escapeHtml(o.admin_note||'')}" placeholder="Admin note"></div></div>`}).join(''):'<p>No orders in this tab.</p>'}
